name: tema2_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - accelerate=1.8.1=pyhe01879c_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.14=pyh7db6752_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.9.0=pyh29332c3_0
  - arrow-cpp=19.0.0=hfcf91c8_3
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.8.5=h5eee18b_0
  - aws-c-cal=0.8.5=hdbd6064_0
  - aws-c-common=0.11.1=h5eee18b_0
  - aws-c-compression=0.3.1=h5eee18b_0
  - aws-c-event-stream=0.5.4=h6a678d5_0
  - aws-c-http=0.9.3=h5eee18b_0
  - aws-c-io=0.17.0=h5eee18b_0
  - aws-c-mqtt=0.12.2=h5eee18b_0
  - aws-c-s3=0.7.11=hdbd6064_0
  - aws-c-sdkutils=0.2.3=h5eee18b_0
  - aws-checksums=0.2.3=h5eee18b_0
  - aws-crt-cpp=0.31.0=h6a678d5_0
  - aws-sdk-cpp=1.11.528=h74f24ce_0
  - backoff=2.2.1=pyhd8ed1ab_1
  - bitsandbytes=0.46.1=cuda126_py311hfd5f2ba_0
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - boost-cpp=1.78.0=he72f1d9_0
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - cffi=1.17.1=py311h1fdaa30_1
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - chromadb=0.3.25=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - clickhouse-connect=0.8.18=py311h9ecbd09_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - cpython=3.11.13=py311hd8ed1ab_0
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-version=12.9=h4f385c5_3
  - dataclasses-json=0.6.7=pyhd8ed1ab_1
  - datasets=3.6.0=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - dnspython=2.7.0=pyhff2d567_1
  - email-validator=2.2.0=pyhd8ed1ab_1
  - email_validator=2.2.0=hd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - faiss=1.9.0=py311cuda126h4491dc0_0_cuda
  - faiss-gpu=1.9.0=h418687c_0
  - fastapi=0.116.1=h26c32bb_1
  - fastapi-cli=0.0.8=pyhd8ed1ab_0
  - fastapi-core=0.116.1=pyhe01879c_1
  - filelock=3.18.0=pyhd8ed1ab_0
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.7.0=pyhf298e5d_0
  - fsspec=2025.3.0=pyhd8ed1ab_0
  - gflags=2.2.2=he1b5a44_1004
  - glog=0.5.0=h48cff8f_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - greenlet=3.2.3=py311hfdbb021_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hnswlib=0.8.0=py311h5b7b71f_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.6.4=py311h9ecbd09_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - httpx-sse=0.4.1=pyhd8ed1ab_0
  - huggingface_hub=0.31.4=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py311h38be061_1
  - krb5=1.21.3=h8a1dbc1_1
  - langchain=0.3.26=pymin39_hff2d567_0
  - langchain-community=0.3.27=pymin39_hff2d567_0
  - langchain-core=0.3.69=pyhd8ed1ab_0
  - langchain-huggingface=0.3.0=pyh885dcc9_0
  - langchain-text-splitters=0.3.8=pyhd8ed1ab_0
  - langsmith=0.3.45=pyhd8ed1ab_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcublas=12.9.1.4=h9ab20c4_0
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcurl=8.14.1=h31d0fb7_0
  - libcusparse=12.5.10.65=h5888daf_1
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hdbd6064_1
  - libfaiss=1.9.0=cuda126h4727808_0_cuda
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=15.1.0=h767d61c_3
  - libgrpc=1.71.0=h2d74bed_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libnghttp2=1.57.0=h2d74bed_0
  - libnvjitlink=12.9.86=h5888daf_1
  - libopenblas=0.3.29=ha39b09d_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.7.0=hde9077f_0
  - libtorch=2.6.0=cpu_openblas_h70a2a0d_6
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - lz4=4.3.3=py311h2cbdf9a_1
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=pyhe1237c8_1
  - marshmallow=3.26.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - monotonic=1.6=pyhd8ed1ab_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=pyh62beb40_0
  - multiprocess=0.70.15=py311h06a4308_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.5=pyhe01879c_0
  - nomkl=3.0=0
  - numexpr=2.11.0=py311hbaae466_0
  - numpy=1.26.4=py311h24aa872_0
  - numpy-base=1.26.4=py311hbfb1bba_0
  - onnxruntime=1.22.0=py311h9b445dc_0_cpu
  - openblas=0.3.29=h06a4308_0
  - openblas-devel=0.3.29=ha39b09d_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.1=h7b32b05_0
  - opentelemetry-api=1.35.0=pyhd8ed1ab_0
  - orc=2.1.1=hd396ef6_0
  - orjson=3.11.0=py311h902ca64_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py311h277b779_0
  - pillow=11.1.0=py311hac6e08b_1
  - pip=25.1=pyhc872135_2
  - posthog=6.1.1=pyhd8ed1ab_0
  - propcache=0.3.1=pyhe1237c8_0
  - protobuf=5.29.3=py311he621ea3_0
  - psutil=5.9.0=py311h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=19.0.0=py311h6a678d5_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py311hdae7d1d_0
  - pydantic-settings=2.10.1=pyh3cfb1c2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pypdf=5.8.0=pyhe01879c_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.13=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.1=pyhe01879c_0
  - python-duckdb=1.3.2=py311h1ddb823_0
  - python-flatbuffers=25.2.10=pyhbc23db3_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py311h5eee18b_0
  - python_abi=3.11=2_cp311
  - pytorch=2.6.0=cpu_openblas_py311h2faf015_6
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=pyhe1237c8_2
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py311h5eee18b_0
  - requests=2.32.4=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - rich=13.9.4=pyhd8ed1ab_1
  - rich-toolkit=0.14.8=pyhe01879c_0
  - s2n=1.5.14=hdbd6064_0
  - safetensors=0.5.3=py311h448de89_0
  - scikit-learn=1.6.1=py311h6a678d5_0
  - scipy=1.15.3=py311h5e4e545_0
  - sentence-transformers=5.0.0=pyhd8ed1ab_0
  - setuptools=78.1.1=py311h06a4308_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.5.1=h9b69904_2
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlalchemy=2.0.41=py311h9ecbd09_0
  - sqlite=3.50.2=hb25bd0a_1
  - starlette=0.47.1=pyh82d4cca_0
  - sympy=1.14.0=pyh2585a3b_105
  - tenacity=9.1.2=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.14=h993c535_1
  - tokenizers=0.21.0=py311h5e3497e_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.53.2=pyhd8ed1ab_0
  - typer=0.16.0=pyh167b9f4_0
  - typer-slim=0.16.0=pyhe01879c_0
  - typer-slim-standard=0.16.0=hf964461_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - typing_inspect=0.9.0=pyhd8ed1ab_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utf8proc=2.6.1=h5eee18b_1
  - uvicorn=0.35.0=pyh31011fe_0
  - uvicorn-standard=0.35.0=h31011fe_0
  - uvloop=0.21.0=py311h5eee18b_0
  - watchfiles=1.1.0=py311h9e33e62_0
  - websockets=15.0.1=py311h9ecbd09_0
  - wheel=0.45.1=py311h06a4308_0
  - wrapt=1.17.0=py311h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f98852_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.20.1=pyhe1237c8_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py311h2c38b39_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - cryptography==45.0.5
      - lxml==6.0.0
      - olefile==0.47
      - pyhwp==0.1b15
